###
@graphqlEndpoint =  {{$dotenv NHOST_GRAPHQL_URL}}
@graphqlAdminToken = {{$dotenv HASURA_GRAPHQL_ADMIN_SECRET}}
@authEndpoint = {{$dotenv NHOST_AUTH_URL}}

# set token without `''`
@graphqlUserToken =
###


### List Security Keys
# @name SearchSecurityKeys
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
# Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user me manager
x-hasura-default-role: user
x-hasura-role: user
x-hasura-allowed-orgs: {chinthagunta,example}
x-hasura-default-org: chinthagunta
x-hasura-user-email: sumo@demo.com
x-hasura-user-id: 076a79f9-ed08-4e28-a4c3-8d4e0aa269a3

query SearchSecurityKeys($userId: uuid!) {
  authUserSecurityKeys(where: { userId: { _eq: $userId } }) {
    id
    nickname
  }
}

{
      "userId": "076a79f9-ed08-4e28-a4c3-8d4e0aa269a3"
}

### List Orgs
# @name GetOrgs
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
# Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user me manager
x-hasura-default-role: user
x-hasura-role: manager
x-hasura-allowed-orgs: {chinthagunta,example}
x-hasura-default-org: chinthagunta
x-hasura-user-email: sumo@demo.com
x-hasura-user-id: 076a79f9-ed08-4e28-a4c3-8d4e0aa269a3

query GetOrganizations {
  organizations {
    allowedEmailDomains
    allowedEmails
    description
    organization
  }
}

### Create PAT
# @name createPAT
POST {{authEndpoint}}/pat
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}

{
  "metadata": {
    "name": "sumodemo"
  },
  "expiresAt": "2024-11-07T05:31:56Z"
}

###
@createdPAT =  {{createPAT.response.body.$.personalAccessToken}}
###

### List PAT tokens
# @name getMyPATs
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
# Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user me manager
x-hasura-default-role: user
x-hasura-role: me
x-hasura-allowed-orgs: {chinthagunta,example}
x-hasura-default-org: chinthagunta
x-hasura-user-email: sumo@demo.com
x-hasura-user-id: 076a79f9-ed08-4e28-a4c3-8d4e0aa269a3

query GetMyPATs {
  users {
    id
    refreshTokens(where: {type: {_eq: pat}}) {
      id
      type
      metadata
      userId
      expiresAt
    }
  }
}


### Signin With PAT
# @name SigninPAT
POST {{authEndpoint}}/signin/pat
Content-Type: application/json

{
  "personalAccessToken": "{{createdPAT}}"
}
