###
@graphqlEndpoint =  {{$dotenv NHOST_GRAPHQL_URL}}
@graphqlAdminToken = {{$dotenv HASURA_GRAPHQL_ADMIN_SECRET}}
@authEndpoint = {{$dotenv NHOST_AUTH_URL}}

# set token without `''`
@accessToken =
###


### List Security Keys
# @name SearchSecurityKeys
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
# Authorization: Bearer {{accessToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user me org:admin
x-hasura-default-role: user
x-hasura-role: user
x-hasura-allowed-orgs: {'8dfd9a31-de01-47be-92a7-ba1c720c6270', 'd5dbb6b6-5e43-4dca-b855-be9b65b6695b'}
x-hasura-default-org: 8dfd9a31-de01-47be-92a7-ba1c720c6270
x-hasura-user-id: 572ad1c0-f97b-4e16-b1f6-8b5ca90f931f

query SearchSecurityKeys($userId: uuid!) {
  authUserSecurityKeys(where: { userId: { _eq: $userId } }) {
    id
    nickname
  }
}

{
      "userId": "076a79f9-ed08-4e28-a4c3-8d4e0aa269a3"
}

### List Orgs
# @name GetOrgs
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
# Authorization: Bearer {{accessToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user me org:admin
x-hasura-default-role: org:admin
x-hasura-role: org:admin
x-hasura-allowed-orgs: {'8dfd9a31-de01-47be-92a7-ba1c720c6270', 'd5dbb6b6-5e43-4dca-b855-be9b65b6695b'}
x-hasura-default-org: 8dfd9a31-de01-47be-92a7-ba1c720c6270
x-hasura-user-id: 572ad1c0-f97b-4e16-b1f6-8b5ca90f931f

query GetOrganizations {
  organizations {
    allowedEmailDomains
    allowedEmails
    description
    organization
  }
}

### Create User
# @name createUser
POST {{authEndpoint}}/signup/email-password
Content-Type: application/json

{
  "email": "john.smith@chinthagunta.com",
  "password": "Str0ngPassw#ord-94|%",
  "options": {
    "displayName": "John Smith",
    "locale": "en",
    "redirectTo": "https://console.traefik.me:5173/dashboard"
  }
}

###
@accessToken = {{createUser.response.body.$.session.accessToken}}
###

### Create User2
# @name createUser2
POST {{authEndpoint}}/signup/email-password
Content-Type: application/json

{
  "email": "david.bowie@species.com",
  "password": "Str0ngPassw#ord-94|%",
  "options": {
    "displayName": "David Bowie",
    "locale": "en",
    "redirectTo": "https://console.traefik.me:5173/dashboard"
  }
}



### SignIn1
# @name signIn
POST {{authEndpoint}}/signin/email-password
Content-Type: application/json

{
  "email": "john.smith@chinthagunta.com",
  "password": "Str0ngPassw#ord-94|%"
}

### SignIn2
# @name signIn
POST {{authEndpoint}}/signin/email-password
Content-Type: application/json

{
  "email": "david.bowie@species.com",
  "password": "Str0ngPassw#ord-94|%"
}

### Create PAT
# @name createPAT
POST {{authEndpoint}}/pat
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "metadata": {
    "name": "sumodemo"
  },
  "expiresAt": "2024-11-07T05:31:56Z"
}

###
@createdPAT =  {{createPAT.response.body.$.personalAccessToken}}
###

### List PAT tokens
# @name getMyPATs
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
# Authorization: Bearer {{accessToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user me org:admin
x-hasura-default-role: user
x-hasura-role: me
x-hasura-allowed-orgs: {'8dfd9a31-de01-47be-92a7-ba1c720c6270', 'd5dbb6b6-5e43-4dca-b855-be9b65b6695b'}
x-hasura-default-org: 8dfd9a31-de01-47be-92a7-ba1c720c6270
x-hasura-user-id: 572ad1c0-f97b-4e16-b1f6-8b5ca90f931f

query GetMyPATs {
  users {
    id
    refreshTokens(where: {type: {_eq: pat}}) {
      id
      type
      metadata
      userId
      expiresAt
    }
  }
}


### Signin With PAT
# @name SigninPAT
POST {{authEndpoint}}/signin/pat
Content-Type: application/json

{
  "personalAccessToken": "{{createdPAT}}"
}
