###
@graphqlEndpoint =  {{$dotenv NHOST_GRAPHQL_URL}}
@graphqlAdminToken = {{$dotenv HASURA_GRAPHQL_ADMIN_SECRET}}
# set token without `''`
@graphqlUserToken =
###

### IntrospectionQuery
# @name IntrospectionQuery
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
x-hasura-admin-secret: {{graphqlAdminToken}}

query IntrospectionQuery {
	__schema {
		types {
			name
			description
		}
		directives {
			name
			description
			locations
		}
	}
}

### List Active Pools
# @name listPools
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user org:admin
x-hasura-default-role: org:admin
x-hasura-role: org:admin
x-hasura-org-ids: {'8dfd9a31-de01-47be-92a7-ba1c720c6270', 'd5dbb6b6-5e43-4dca-b855-be9b65b6695b'}
x-hasura-org-id: 8dfd9a31-de01-47be-92a7-ba1c720c6270
x-hasura-user-id: 572ad1c0-f97b-4e16-b1f6-8b5ca90f931f

query SearchPoolsAndDevices($limit: Int = 10, $offset: Int = 0, $filter: String!) {
  pools(limit: $limit, offset: $offset, where: {displayName: {_like: $filter}}, order_by: [{updatedAt: desc_nulls_last}]) {
    id
    displayName
  }
  devices(limit: $limit, offset: $offset, where: {displayName: {_like: $filter}}, order_by: [{updatedAt: desc_nulls_last}]) {
    id
    displayName
  }
}

{
  "filter": "%%"
}
