###
@graphqlEndpoint =  {{$dotenv PUBLIC_GRAPHQL_ENDPOINT}}
@graphqlAdminToken = {{$dotenv HASURA_GRAPHQL_ADMIN_SECRET}}
# set token without `''`
@graphqlUserToken =
###

### IntrospectionQuery
# @name IntrospectionQuery
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
x-hasura-admin-secret: {{graphqlAdminToken}}

query IntrospectionQuery {
	__schema {
		types {
			name
			description
		}
		directives {
			name
			description
			locations
		}
	}
}

### List Active Pools
# @name listPools
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager
x-hasura-default-role: manager
x-hasura-role: manager
x-hasura-allowed-orgs: {chinthagunta}
x-hasura-default-org: chinthagunta
x-hasura-user-id: 076a79f9-ed08-4e28-a4c3-8d4e0aa269a3

query SearchPoolsAndDevices($limit: Int = 10, $offset: Int = 0, $filter: String!) {
  pools(limit: $limit, offset: $offset, where: {displayName: {_like: $filter}}, order_by: [{updatedAt: desc_nulls_last}]) {
    id
    displayName
  }
  devices(limit: $limit, offset: $offset, where: {displayName: {_like: $filter}}, order_by: [{updatedAt: desc_nulls_last}]) {
    id
    displayName
  }
}

{
  "filter": "%%"
}
