###
@graphqlEndpoint =  {{$dotenv NHOST_GRAPHQL_URL}}
@graphqlAdminToken = {{$dotenv HASURA_GRAPHQL_ADMIN_SECRET}}
# set token without `''`
@graphqlUserToken =  'get me from OAuth flow'
###

### show settings data
# @name Settings
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user me org:admin
x-hasura-default-role: org:admin
x-hasura-allowed-orgs: {"8dfd9a31-de01-47be-92a7-ba1c720c6270", "d5dbb6b6-5e43-4dca-b855-be9b65b6695b"}
x-hasura-default-org: 8dfd9a31-de01-47be-92a7-ba1c720c6270
x-hasura-user-id: 572ad1c0-f97b-4e16-b1f6-8b5ca90f931f

query SettingsData($id: uuid!) {
  organizations_by_pk(id: $id) {
    ...SettingsFragment
    ...SettingsWithDefaultsFragment
    id
  }
  settings_metadata(order_by: {key: asc}) {
    key
    description
    allowed_values
    default_value
  }
}
fragment SettingsFragment on organizations {
  settings(order_by: {key: asc}) {
    key
    value
  }
  id
  __typename
}
fragment SettingsWithDefaultsFragment on organizations {
  settingsWithDefaults(order_by: {key: asc}) {
    key
    value
  }
  id
  __typename
}

{
  "id": "8dfd9a31-de01-47be-92a7-ba1c720c6270"
}

### show settings data
# @name Settings2
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user me org:admin
x-hasura-default-role: org:admin
x-hasura-allowed-orgs: {"d5dbb6b6-5e43-4dca-b855-be9b65b6695b"}
x-hasura-default-org: d5dbb6b6-5e43-4dca-b855-be9b65b6695b
x-hasura-user-id: bacd19f4-0cc4-43d1-9e7a-4e5098ed8d83

query SettingsData($id: uuid!) {
  organizations_by_pk(id: $id) {
    ...SettingsFragment
    ...SettingsWithDefaultsFragment
    id
  }
  settings_metadata(order_by: {key: asc}) {
    key
    description
    allowed_values
    default_value
  }
}
fragment SettingsFragment on organizations {
  settings(order_by: {key: asc}) {
    key
    value
  }
  id
  __typename
}
fragment SettingsWithDefaultsFragment on organizations {
  settingsWithDefaults(order_by: {key: asc}) {
    key
    value
  }
  id
  __typename
}

{
  "id": "d5dbb6b6-5e43-4dca-b855-be9b65b6695b"
}
