name: Setup
description: Setup environment and cache

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
    - run: pnpm install
      shell: bash
    - run: pnpm add --global turbo
      shell: bash
