version: '3.9'
services:
  ###########################################################################
  # hasura service - dev mode
  ###########################################################################
  hasura:
    ## User `cli-migrations-v3` only in local dev env.
    ## It will automatically apply Migrations and Metadata to a Hasura GraphQL Engine
    image: hasura/graphql-engine:v2.37.0.cli-migrations-v3
    volumes:
      - ./nhost/migrations:/hasura-migrations
      - ./nhost/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  ###########################################################################
  # hasura auth
  ###########################################################################
  auth:
    environment:
      # AUTH_DEBUG: true
      AUTH_SHOW_LOG_QUERY_PARAMS: true
