version: '3.8'

services:
  webapp:
    image: ghcr.io/xmlking/spectacular:latest
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      ORIGIN: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      AUTH_TRUST_HOST: true
      PUBLIC_GRAPHQL_ENDPOINT: http://0.0.0.0:8080/v1/graphql
    env_file:
      - .env
    ports:
      - 3000:3000

  mesh:
    image: ghcr.io/xmlking/graphql-mesh:v0.1.0
    restart: always
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
    volumes:
      - ./.meshrc.yml:/app/.meshrc.yml:ro
    tmpfs:
      - /app/.mesh:exec,mode=777

  postgres:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/db_scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
      -c wal_level=logical
      -c max_wal_senders=1
      -c max_replication_slots=1
    #   -c listen_addresses = '*'

  hasura:
    ## User `cli-migrations-v3` only in local dev env. It will automatically apply Migrations and Metadata to a Hasura GraphQL Engine
    image: hasura/graphql-engine:v2.34.0.cli-migrations-v3
    platform: linux/arm64/v8
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=allow
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=allow
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET:-myadminsecretkey}
      # HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS512", "jwk_url": "https://www.googleapis.com/oauth2/v3/certs"}'
      # HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "1084d8d404126d641c232604aa27bc756921c07a5869c6de6cfd0c6c455de0fe" }'
      HASURA_GRAPHQL_JWT_SECRET: |
        {
          "type": "HS256",
          "key": "1084d8d404126d641c232604aa27bc756921c07a5869c6de6cfd0c6c455de0fe",
          "claims_map": {
            "x-hasura-allowed-roles": { "path": "$.roles" },
            "x-hasura-default-role": "anonymous",
            "x-hasura-user-id": { "path": "$.email" },
            "x-hasura-org-id":  { "path": "$.org", "default": "public" }
          }
        }
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_CORS_DOMAIN: '*'
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: 'true'
      ## enable allowList only for prod if required
      # HASURA_GRAPHQL_ENABLE_ALLOWLIST: 'true'
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
    healthcheck:
      test: curl --fail -s http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 15s
      retries: 3
    volumes:
      - ./infra/hasura/migrations:/hasura-migrations
      - ./infra/hasura/metadata:/hasura-metadata

  hasura-auth:
    container_name: hasura-auth
    image: onlydustxyz/hasura-auth:latest
    depends_on:
      db:
        condition: service_healthy
      hasura:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db/marketplace_db
      HASURA_GRAPHQL_GRAPHQL_URL: http://hasura:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET:-myadminsecretkey}
      AUTH_ACCESS_TOKEN_EXPIRES_IN: 604800 # 1 week
      AUTH_JWT_CUSTOM_CLAIMS: '{"projectsLeaded":"registeredUser.projectsLeaded[].projectId","githubUserId":"registeredUser.githubUserId","odAdmin":"registeredUser.admin","githubAccessToken":"userGithubProvider.accessToken"}'
      AUTH_USER_DEFAULT_ALLOWED_ROLES: public,me,registered_user
      AUTH_USER_DEFAULT_ROLE: registered_user
      AUTH_LOG_LEVEL: info
      AUTH_CLIENT_URL: http://localhost:5173
      AUTH_PROVIDER_GITHUB_ENABLED: 'true'
      AUTH_SERVER_URL: http://localhost:4000
      AUTH_PROVIDER_GITHUB_CLIENT_ID: ${AUTH_PROVIDER_GITHUB_CLIENT_ID:-my_github_client_id}
      AUTH_PROVIDER_GITHUB_CLIENT_SECRET: ${AUTH_PROVIDER_GITHUB_CLIENT_SECRET:-my_github_client_secret}
      AUTH_SMTP_HOST: smtp-relay.sendinblue.com
      AUTH_SMTP_PORT: 587
      AUTH_SMTP_AUTH_METHOD: LOGIN
      AUTH_SMTP_SECURE: false
      AUTH_SMTP_USER: xmlking@gmail.com
      AUTH_SMTP_PASS: ${AUTH_SMTP_PASS}
      AUTH_SMTP_SENDER: sumodemo123@gmail.com
    ports:
      - '4000:4000'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4000/healthz || exit 1
      interval: 2s
      timeout: 1s
      retries: 30

volumes:
  db_data:
