packages:
  - "apps/*"
  - "packages/*"
 # exclude some packages
  - "!apps/urara"

catalog:
  "@types/dom-chromium-ai": 0.0.7
  "@aibrow/dom-types": 2.0.2
  "@inlang/paraglide-js": 2.0.13
  "@sveltejs/kit": 2.21.0 # https://github.com/sveltejs/kit/issues/13804
  "@types/node": 22.15.29
  "@lucide/svelte": 0.511.0
  "@playwright/test": 1.52.0
  "@biomejs/biome": 2.0.0-beta.5
  vitest: 3.1.4
  "@vitest/ui": 3.1.4
  "@vitest/coverage-v8": 3.1.4
  typescript: 5.8.3
  turbo: 2.5.4
  zod: 3.25.46
  cspell: 9.0.2
  bits-ui: 2.4.1
  svelte-sonner: 1.0.4
  svelte-check: 4.2.1
  houdini: 1.5.6
  flags: 4.0.1

catalogs:
  svelte4:
    svelte: 4.2.19
    "@ai-sdk/svelte": 1.1.24
    "@sveltejs/vite-plugin-svelte": 3.1.2
    "@xyflow/svelte": 0.1.37
    "@inlang/paraglide-sveltekit": 0.14.0
    "@sveltejs/enhanced-img": 0.3.10
    formsnap: 1.0.1
    vite: 5.4.18
    "@skeletonlabs/skeleton": 2.11.0
    svelte-meta-tags: 3.1.4
    tailwind-merge: 2.6.0
    tailwind-variants: 0.3.1
    tailwindcss: 3.4.17

  svelte5:
    svelte: 5.33.13
    "@ai-sdk/svelte": 2.1.12
    "@sveltejs/enhanced-img": 0.6.0
    "@sveltejs/vite-plugin-svelte": 5.0.3
    formsnap: 2.0.1
    vite: 6.3.5
    # vite: npm:rolldown-vite@latest
    "@skeletonlabs/skeleton": 3.1.3
    svelte-meta-tags: 4.3.0
    tailwind-merge: 3.3.0
    tailwind-variants: 1.0.0
    tailwindcss: 4.1.8
