packages:
  - apps/*
  - packages/*

catalog:
  '@changesets/cli': 2.29.5
  '@changesets/changelog-github': 0.5.1
  '@dotenv-run/cli': 1.3.6
  '@types/bun': 1.2.16
  '@types/node': 24.0.13
  '@types/dom-chromium-ai': 0.0.9
  '@aibrow/dom-types': 2.0.5
  '@inlang/paraglide-js': 2.2.0
  '@sveltejs/kit': https://pkg.pr.new/sveltejs/kit/@sveltejs/kit@13957
  '@lucide/svelte': 0.525.0
  '@biomejs/biome': 2.1.1
  '@turbo/gen': 2.5.4
  '@playwright/test': 1.54.1
  '@ai-sdk/svelte': 2.1.12
  '@sveltejs/enhanced-img': 0.6.1
  '@sveltejs/vite-plugin-svelte': 6.0.0
  '@skeletonlabs/skeleton': 3.1.3
  '@testing-library/dom': 10.4.0
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/svelte': 5.2.8
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  '@vitest/browser': 3.2.4
  jsdom: 26.1.0
  turbo: 2.5.4
  tailwindcss: 4.1.11
  tailwind-merge: 3.3.1
  tw-animate-css: 1.3.5
  tailwind-variants: 1.0.0
  typescript: 5.8.3
  svelte: https://pkg.pr.new/svelte@15844
  formsnap: 2.0.1
  svelte-meta-tags: 4.3.0
  cspell: 9.1.3
  bits-ui: 2.8.10
  svelte-sonner: 1.0.5
  svelte-check: 4.2.2
  houdini: 1.5.8
  flags: 4.0.1
  playwright: 1.54.1
  vite: 7.0.4
  vite-plugin-devtools-json: 0.2.1
  vitest: 3.2.4
  vitest-browser-svelte: 1.0.0
  zod: 4.0.5

catalogs:
  svelte4:
    '@ai-sdk/svelte': 1.1.24
    '@sveltejs/vite-plugin-svelte': 3.1.2
    '@xyflow/svelte': 0.1.39
    '@inlang/paraglide-sveltekit': 0.14.0
    '@sveltejs/enhanced-img': 0.3.10
    '@skeletonlabs/skeleton': 2.11.0
    '@sveltejs/kit': 2.21.0
    formsnap: 1.0.1
    svelte: 4.2.20
    svelte-meta-tags: 3.1.4
    tailwindcss: 3.4.17
    tailwind-merge: 2.6.0
    tailwind-variants: 0.3.1
    vite: 5.4.18

# overrides:
#   '@dotenv-run/core': 1.3.6
