packages:
  - apps/*
  - packages/*

catalog:
  '@changesets/cli': 2.29.4
  '@changesets/changelog-github': 0.5.1
  '@dotenv-run/cli': 1.3.6
  '@types/bun': 1.2.16
  '@types/node': 24.0.1
  '@types/dom-chromium-ai': 0.0.7
  '@aibrow/dom-types': 2.0.2
  '@inlang/paraglide-js': 2.1.0
  '@sveltejs/kit': 2.21.5
  '@lucide/svelte': 0.515.0
  '@biomejs/biome': 2.0.0-beta.6
  '@turbo/gen': 2.5.4
  '@playwright/test': 1.53.0
  '@ai-sdk/svelte': 2.1.12
  '@sveltejs/enhanced-img': 0.6.0
  '@sveltejs/vite-plugin-svelte': 5.1.0
  '@skeletonlabs/skeleton': 3.1.3
  '@vitest/coverage-v8': 3.2.3
  '@vitest/ui': 3.2.3
  turbo: 2.5.4
  tailwindcss: 4.1.10
  tailwind-merge: 3.3.1
  tw-animate-css: 1.3.4
  tailwind-variants: 1.0.0
  typescript: 5.8.3
  svelte: 5.34.3
  formsnap: 2.0.1
  svelte-meta-tags: 4.3.0
  cspell: 9.1.1
  bits-ui: 2.7.0
  svelte-sonner: 1.0.5
  svelte-check: 4.2.1
  houdini: 1.5.7
  flags: 4.0.1
  vite: 6.3.5
  vitest: 3.2.3
  zod: 3.25.64

catalogs:
  svelte4:
    '@ai-sdk/svelte': 1.1.24
    '@sveltejs/vite-plugin-svelte': 3.1.2
    '@xyflow/svelte': 0.1.39
    '@inlang/paraglide-sveltekit': 0.14.0
    '@sveltejs/enhanced-img': 0.3.10
    '@skeletonlabs/skeleton': 2.11.0
    '@sveltejs/kit': 2.21.0
    formsnap: 1.0.1
    svelte: 4.2.20
    svelte-meta-tags: 3.1.4
    tailwindcss: 3.4.17
    tailwind-merge: 2.6.0
    tailwind-variants: 0.3.1
    vite: 5.4.18
