name = 'console'

[image]
image = 'ghcr.io/xmlking/spectacular/console:0.4.3'
pullCredentials = '{{ secrets.CONTAINER_REGISTRY_CREDENTIALS }}'

# runtime
[[environment]]
NAME = 'NODE_ENV'
VALUE = 'development'

[[environment]]
NAME = 'VERCEL_ENV'
VALUE = 'development'

# deployment environment
[[environment]]
name = 'NHOST_SUBDOMAIN'
value = 'local'

[[environment]]
name = 'PUBLIC_NHOST_REGION'
value = 'local'

[[environment]]
name = 'PUBLIC_NHOST_SUBDOMAIN'
value = 'local'

[[environment]]
name = 'PUBLIC_NHOST_REGION'
value = 'local'

# hasura, storage, auth
[[environment]]
name = 'NHOST_HASURA_URL'
value = 'https://local.hasura.local.nhost.run/console'

[[environment]]
name = 'NHOST_AUTH_URL'
value = 'https://local.auth.local.nhost.run/v1'

[[environment]]
name = 'NHOST_GRAPHQL_URL'
value = 'https://local.hasura.local.nhost.run/v1/graphql'

[[environment]]
name = 'NHOST_STORAGE_URL'
value =   'https://local.storage.local.nhost.run/v1'

[[environment]]
name = 'NHOST_FUNCTIONS_URL'
value = 'https://local.functions.local.nhost.run/v1'

[[environment]]
name = 'PUBLIC_NHOST_AUTH_URL'
value = 'https://local.auth.local.nhost.run/v1'

[[environment]]
name = 'PUBLIC_NHOST_GRAPHQL_URL'
value = 'https://local.hasura.local.nhost.run/v1/graphql'

[[environment]]
name = 'PUBLIC_NHOST_STORAGE_URL'
value = 'https://local.storage.local.nhost.run/v1'

[[environment]]
name = 'PUBLIC_NHOST_FUNCTIONS_URL'
value = 'https://local.functions.local.nhost.run/v1'

[[environment]]
name = 'HASURA_GRAPHQL_ENDPOINT'
value = 'https://local.hasura.local.nhost.run'

# app
[[environment]]
name = 'APP_NAME'
value = 'Spectacular'

[[environment]]
name = 'APP_DESCRIPTION'
value = 'Spectacular Console App'

[[environment]]
name = 'PUBLIC_DEFAULT_ORGANIZATION'
value = 'chinthagunta'

# terms
[[environment]]
name = 'PUBLIC_TERMS_PRIVACY_COMPANY'
value = 'Your Company'

[[environment]]
name = 'PUBLIC_TERMS_PRIVACY_EFFECTIVE_DATE'
value = 'January 1, 2024'

[[environment]]
name = 'PUBLIC_TERMS_PRIVACY_WEBSITE'
value = 'yourdomain.com'

[[environment]]
name = 'PUBLIC_TERMS_PRIVACY_CONTACT_EMAIL'
value = 'yourname@email.com'

[[environment]]
name = 'PUBLIC_TERMS_PRIVACY_APP_NAME'
value = 'Spectacular'

[[environment]]
name = 'PUBLIC_TERMS_PRIVACY_APP_PRICING_AND_SUBSCRIPTIONS'
value = '[Details about the pricing, subscription model, refund policy]'

[[environment]]
name = 'PUBLIC_TERMS_PRIVACY_COUNTRY'
value = 'United States'

# flags
[[environment]]
name = 'FEATURE_SHOW_MAGIC_LINK_LOGIN'
value = 'true'

[[environment]]
name = 'FEATURE_SHOW_SOCIAL_LOGIN'
value = 'true'

[[environment]]
name = 'FEATURE_SIMULATE_LOADING_STATE'
value = 'false'

# secrets
[[environment]]
name = 'RATE_LIMIT_SECRET'
value = '{{ secrets.RATE_LIMIT_SECRET }}'

[[environment]]
name = 'FLAGS_SECRET'
value = '{{ secrets.FLAGS_SECRET }}'

[[environment]]
name = 'OPENAI_ORG_ID'
value =  '{{ secrets.OPENAI_ORG_ID }}'

[[environment]]
name = 'OPENAI_PROJECT_ID'
value = '{{ secrets.OPENAI_PROJECT_ID }}'

[[environment]]
name = 'OPENAI_API_KEY'
value = '{{ secrets.OPENAI_API_KEY }}'

[[environment]]
name = 'ORIGIN'
value = 'http://localhost:3000'

[[ports]]
port = 3000
type = 'http'
publish = true

# [healthCheck]
# port = 8080
# initialDelaySeconds = 30
# probePeriodSeconds = 60

[resources]
replicas = 1

[resources.compute]
cpu = 62
memory = 128

# [[resources.storage]]
# name='data'
# path='/var/lib/data'
# capacity=1
