fragment Policy_all_fields on policies {
	id
	weight
	active
	validFrom
	validTo
	subjectId
	subjectType
	subjectDisplayName
	subjectSecondaryId
	createdBy
	createdAt
	updatedAt
	updatedBy
	organization
	rule {
		id
		displayName
		description
		tags
		annotations
		shared
		source
		sourcePort
		destination
		destinationPort
		protocol
		direction
		action
		appId
		throttleRate
		weight
		createdBy
		createdAt
		updatedAt
		updatedBy
		organization
	}
}
