mutation DeleteRule($id: uuid!, $deletedAt: timestamptz!) {
	# CASCADING SOFT DELETE POLICIES
	updateRulesByPk(pkColumns: { id: $id }, _set: { deletedAt: $deletedAt }) {
		displayName
	}
	updatePolicies(where: { ruleId: { _eq: $id } }, _set: { deletedAt: $deletedAt }) {
		affectedRows
		returning {
			id
		}
	}
}

# mutation DeleteRule($id: uuid!) {
# 	delete_rules_by_pk(id: $id) {
# 		displayName
# 	}
# }
