mutation UpdatePolicy(
	$policyId: uuid!
	$policyData: PoliciesSetInput!
	$ruleId: uuid!
	$ruleData: RulesSetInput!
	$skipRuleUpdate: Boolean = false
) {
	updatePoliciesByPk(pkColumns: { id: $policyId }, _set: $policyData) {
		id
		subjectDisplayName
		updatedAt
	}
	updateRulesByPk(pkColumns: { id: $ruleId }, _set: $ruleData) @skip(if: $skipRuleUpdate) {
		id
		displayName
		updatedAt
	}
}
