query GetPool($id: uuid!) @cache(policy: NetworkOnly) {
	pools_by_pk(id: $id) {
		annotations
		createdAt
		createdBy
		deletedAt
		description
		displayName
		id
		organization
		tags
		updatedAt
		updatedBy
		pool_devices(limit: 10, order_by: { updatedAt: desc_nulls_last }) {
			associationId: id
			device {
				id
				displayName
				description
				ip
				version
				organization
				updatedAt
				updatedBy
				tags
				annotations
			}
		}
	}
	devices_not_in_pool(args: { poolid: $id }, order_by: { updatedAt: desc_nulls_last }) {
		id
		displayName
		description
		ip
		version
		organization
		updatedAt
		updatedBy
		tags
		updatedAt
	}
}
