query GetPool($id: uuid!) @cache(policy: NetworkOnly) {
	poolsByPk(id: $id) {
		annotations
		createdAt
		createdBy
		deletedAt
		description
		displayName
		id
		organization
		tags
		updatedAt
		updatedBy
		pool_devices(limit: 10, orderBy: { updatedAt: DESC_NULLS_LAST }) {
			associationId: id
			device {
				id
				displayName
				description
				ip
				version
				organization
				updatedAt
				updatedBy
				tags
				annotations
			}
		}
	}
	devicesNotInPool(args: { poolid: $id }, orderBy: { updatedAt: DESC_NULLS_LAST }) {
		id
		displayName
		description
		ip
		version
		organization
		updatedAt
		updatedBy
		tags
		updatedAt
	}
}
