query SearchDevices(
	$where: DevicesBoolExp
	$limit: Int = 50
	$offset: Int = 0
	$orderBy: [DevicesOrderBy!] = [{ updatedAt: DESC_NULLS_LAST }]
) {
	devices(orderBy: $orderBy, limit: $limit, offset: $offset, where: $where) {
		id
		displayName
	}
}
