query SearchPools(
	$where: PoolsBoolExp
	$limit: Int = 50
	$offset: Int = 0
	$orderBy: [PoolsOrderBy!] = [{ updatedAt: DESC_NULLS_LAST }]
) {
	pools(orderBy: $orderBy, limit: $limit, offset: $offset, where: $where) {
		id
		displayName
	}
}
