query SearchRules(
	$where: RulesBoolExp
	$limit: Int = 50
	$offset: Int = 0
	$orderBy: [RulesOrderBy!] = [{ updatedAt: DESC_NULLS_LAST }]
) @cache(policy: NetworkOnly) {
	rules(orderBy: $orderBy, limit: $limit, offset: $offset, where: $where) {
		id
		displayName
		description
		tags
		annotations
		shared
		source
		sourcePort
		destination
		destinationPort
		protocol
		direction
		action
		appId
		throttleRate
		weight
		updatedBy
		updatedAt
	}
}
