apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: console
  app.kubernetes.io/instance: console-abcxzy
  app.kubernetes.io/component: microservice

namePrefix: console-

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: env-vars
    literals:
      - MICRO_SERVER_NAME=gkit.service.console
      # - MICRO_SERVER_ADVERTISE="$(CONSOLE_SERVICE_ENDPOINT):3000"
      # - DATABASE_HOST=$(DATABASE_ENDPOINT)

replacements:
  - path: replacement.yaml
	
# vars:
#   - name: CONSOLE_SERVICE_ENDPOINT
#     objref:
#       kind: Service
#       name: service
#       apiVersion: v1
#     fieldref:
#       fieldpath: metadata.name
