query Memberships($id: OrgIdFromSession!) {
  memberships(where: { orgId: { _eq: $id } })@list(name: "Search_Memberships") {
    userId
    orgId
    role
    updatedAt
    user {
      displayName
      avatarUrl
      email
    }
  }
}
