query Memberships($id: OrgIdFromSession!) {
  memberships(where: { orgId: { _eq: $id } })@list(name: "Search_Memberships") {
    user {
      id
      displayName
      avatarUrl
      email
    }
    role
    updatedAt
  }
}
