// import { env as secrets } from '$env/dynamic/private';

// TODO: enaable after setting - prerender: { crawl: true }
// export const prerender = true;

/*
export const config = {
  isr: {
    // Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
    // Setting the value to `false` means it will never expire.
    expiration: 3600,
    // Random token that can be provided to bypass the cached version of the page with a __prerender_bypass=<token> cookie.
    // Allows rendering content at request time for this route.
    //  The `bypassToken` argument for `Prerender` must be 32 characters or more.
    bypassToken: secrets.FLAGS_SECRET,
  },
};
*/

export async function GET({ setHeaders }) {
  setHeaders({
    'Content-Type': 'application/json',
  });

  // ref: https://web.dev/articles/webauthn-related-origin-requests
  const json = {
    origins: [
      'https://console.traefik.me:5173',
      'https://console.traefik.me:3000',
      'https://console.traefik.me:4173',
      'https://spectacular-console.vercel.app',
      'https://spectacular-console-git-main-spectacular.vercel.app',
    ],
  };

  return new Response(JSON.stringify(json));
}
