table:
  name: org_settings
  schema: public
insert_permissions:
  - role: org:admin
    permission:
      check: {}
      set:
        created_by: x-hasura-User-Id
        org_id: x-hasura-Org-Id
        updated_by: x-hasura-User-Id
      columns:
        - key
        - value
    comment: ""
select_permissions:
  - role: org:admin
    permission:
      columns:
        - value
        - key
        - created_at
        - updated_at
        - created_by
        - org_id
        - updated_by
      filter:
        org_id:
          _eq: X-Hasura-Org-Id
      allow_aggregations: true
    comment: ""
update_permissions:
  - role: org:admin
    permission:
      columns:
        - value
      filter:
        org_id:
          _eq: X-Hasura-Org-Id
      check: null
      set:
        updated_by: x-hasura-User-Id
    comment: ""
delete_permissions:
  - role: org:admin
    permission:
      filter:
        org_id:
          _eq: X-Hasura-Org-Id
    comment: ""
