table:
  name: org_settings_with_defaults
  schema: public
configuration:
  column_config:
    created_at:
      custom_name: createdAt
    created_by:
      custom_name: createdBy
    org_id:
      custom_name: orgId
    updated_at:
      custom_name: updatedAt
    updated_by:
      custom_name: updatedBy
  custom_column_names:
    created_at: createdAt
    created_by: createdBy
    org_id: orgId
    updated_at: updatedAt
    updated_by: updatedBy
  custom_root_fields: {}
select_permissions:
  - role: org:admin
    permission:
      columns:
        - value
        - key
        - created_at
        - updated_at
        - created_by
        - org_id
        - updated_by
      filter:
        org_id:
          _eq: x-hasura-default-org
      allow_aggregations: true
    comment: ""
