table:
  name: settings_metadata
  schema: public
configuration:
  column_config:
    allowed_values:
      custom_name: allowedValues
    default_value:
      custom_name: defaultValue
  custom_column_names:
    allowed_values: allowedValues
    default_value: defaultValue
  custom_root_fields: {}
insert_permissions:
  - role: sys:admin
    permission:
      check: {}
      columns:
        - allowed_values
        - default_value
        - description
        - key
        - type
    comment: ""
select_permissions:
  - role: org:admin
    permission:
      columns:
        - allowed_values
        - default_value
        - description
        - key
        - type
      filter: {}
      allow_aggregations: true
    comment: ""
  - role: sys:admin
    permission:
      columns:
        - allowed_values
        - default_value
        - description
        - key
        - type
      filter: {}
      allow_aggregations: true
    comment: ""
  - role: user
    permission:
      columns:
        - allowed_values
        - default_value
        - description
        - key
        - type
      filter:
        type:
          _eq: user
    comment: ""
update_permissions:
  - role: sys:admin
    permission:
      columns:
        - allowed_values
        - default_value
        - description
        - key
        - type
      filter: {}
      check: {}
    comment: ""
delete_permissions:
  - role: sys:admin
    permission:
      filter: {}
    comment: ""
