# CacheOrNetwork is default cache strategy.
# We are leveraging Houdini's Optimistic updates for this usecase
query GetUser($userId: uuid!) @role(name: "me") {
  # get all fragments needed for profile page.
  user(id: $userId) @loading(cascade: true) {
    email
    ...UserDetailsFragment
    ...UserOrgRolesFragment
    ...PersonalAccessTokensFragment
    ...AuthProvidersFragment
    ...SecurityKeysFragment
  }
}

