apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: docs
  app.kubernetes.io/instance: docs-abcxzy
  app.kubernetes.io/component: microservice

namePrefix: docs-

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: env-vars
    literals:
      - MICRO_SERVER_NAME=gkit.service.docs
      # - MICRO_SERVER_ADVERTISE="$(DOCS_SERVICE_ENDPOINT):3000"
      # - DATABASE_HOST=$(DATABASE_ENDPOINT)
# vars:
#   - name: DOCS_SERVICE_ENDPOINT
#     objref:
#       kind: Service
#       name: service
#       apiVersion: v1
#     fieldref:
#       fieldpath: metadata.name
