###
@graphqlEndpoint =  {{$dotenv HASURA_GRAPHQL_ENDPOINT}}/v1/graphql
@graphqlAdminToken = {{$dotenv HASURA_GRAPHQL_ADMIN_SECRET}}
# set token without `''`
@graphqlUserToken =
###

### IntrospectionQuery
# @name IntrospectionQuery
POST  {{graphqlEndpoint}}
Content-Type: application/json
x-hasura-admin-secret: {{graphqlAdminToken}}
X-REQUEST-TYPE: GraphQL

query IntrospectionQuery {
	__schema {
		types {
			name
			description
		}
		directives {
			name
			description
			locations
		}
	}
}

### List Active Devices
# @name listDevices
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager engine
x-hasura-role: engine
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

query ListDevices($limit: Int = 50, $offset: Int = 0, $order_by: [devices_order_by!] = [{updatedAt: desc_nulls_last}]) {
  devices(limit: $limit, offset: $offset, order_by: $order_by) {
    ip
	tags
	createdBy
	description
	displayName
	organization
    updatedBy
	createdAt
	deletedAt
	updatedAt
	annotations
	id
  }
}

{
  "limit": 5,
  "offset": 0
}

### Search Active Devices
# @name searchDevices
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager engine
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com


query SearchDevices($where: devices_bool_exp, $limit: Int = 50, $offset: Int = 0, $orderBy: [devices_order_by!] = [{updatedAt: desc_nulls_last}]) {
  devices(order_by: $orderBy, limit: $limit, offset: $offset, where: $where) {
    ip
    tags
    createdBy
    description
    displayName
    organization
    updatedBy
    createdAt
    deletedAt
    updatedAt
    annotations
    id
  }
}

{
  "where": {
    "displayName": { "_like": "%test%" }
  },
  "limit": 10
}

###
@firstDeviceId =  {{listDevices.response.body.$.data.devices[0].id}}
###

### getDevice by Id
# @name getDevice
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager engine
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

query GetDevice($id: uuid!) {
  devices_by_pk(id: $id) {
    id
	ip
    displayName
    description
    organization
    tags
    annotations
    createdAt
    createdBy
    updatedAt
    updatedBy
    deletedAt
  }
}

{
  "id": "{{firstDeviceId}}"
}

### update device by ID
# organization = x-hasura-org-id 	updated_by = x-hasura-user-id
# @name updateDevice
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager engine
x-hasura-role: engine
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

mutation UpdateDevice($id: uuid!, $data: devices_set_input!) {
  update_devices_by_pk(pk_columns: { id: $id }, _set: $data) {
    id
	displayName
	description
    updatedAt
  }
}

{
  "id":"{{firstDeviceId}}",
  "data":{
    "description":"user 1 device v3",
    "tags":["tz","us"],
    "annotations":"\"sumo\"=>\"demo3\""
  }
}

### UPSERT: create new device if displayName not already exist, otherwise update
# organization = x-hasura-org-id 	created_by = x-hasura-user-id
# @name createDevice
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager engine
x-hasura-role: engine
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

mutation CreateDevice($data: devices_insert_input!) {
  insert_devices_one(object: $data, on_conflict: {update_columns: [ip, description, tags, annotations], constraint: devices_display_name_organization_key, where: {deletedAt: {_is_null: true}}}) {
    annotations
    ip
    id
    displayName
    tags
    organization
    description
    createdAt
    createdBy
    updatedAt
    updatedBy
    deletedAt
  }
}


{
  "data":{
    "annotations": "\"sumo\"=>\"demo\"",
    "displayName": "test-ddd",
    "ip": "1.1.1.2"
  }
}

###
@createdDeviceId =  {{createDevice.response.body.$.data.insert_devices_one.id}}
###

### Delete Device
# if null returned, either ID is not found or this user don't have permissions to delete
# @name deleteDevice
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager engine admin
x-hasura-role: admin
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

mutation DeleteDevice($id: uuid!, $deletedAt: timestamptz!) {
	update_devices_by_pk(pk_columns: { id: $id }, _set: { deletedAt: $deletedAt }) {
		displayName
	}
}

{
  "id": "{{createdDeviceId}}",
  "deletedAt": "{{$localDatetime iso8601}}"
}
