###
@graphqlEndpoint =  {{$dotenv HASURA_GRAPHQL_ENDPOINT}}/v1/graphql
@graphqlAdminToken = {{$dotenv HASURA_GRAPHQL_ADMIN_SECRET}}
# set token without `''`
@graphqlUserToken =
###

### IntrospectionQuery
# @name IntrospectionQuery
POST {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

query IntrospectionQuery {
	__schema {
		types {
			name
			description
		}
		directives {
			name
			description
			locations
		}
	}
}

### list all active policies
# @name listPolicies
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

query ListPolicies(
  $limit: Int = 50
  $offset: Int = 0
  $orderBy: [policies_order_by!] = [{ updatedAt: desc_nulls_last }]
) {
  policies(
	order_by: $orderBy
    limit: $limit
    offset: $offset
  ) {
    id
    weight
    active
    validFrom
    validTo
    subjectId
    subjectType
    subjectDisplayName
    subjectSecondaryId
    createdBy
    createdAt
    updatedAt
    updatedBy
    organization
    rule {
      id
      displayName
      description
      tags
      annotations
      shared
      source
      sourcePort
      destination
      destinationPort
      protocol
      direction
      action
      appId
	  throttleRate
      weight
      createdBy
      createdAt
      updatedAt
      updatedBy
      organization
    }
  }
}

{
  "limit": 5,
  "offset": 0
}

### search active policies for engine
# @name searchAgentPolicies
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager engine
x-hasura-role: engine
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

query SearchAgentPolicies($where: policies_bool_exp, $limit: Int = 50, $offset: Int = 0, $orderBy: [policies_order_by!] = [{updatedAt: desc_nulls_last}]) {
  policies(order_by: $orderBy, limit: $limit, offset: $offset, where: $where) {
    id
    weight
    validFrom
    validTo
    subjectId
    subjectType
    subjectSecondaryId
    rule {
      id
      displayName
      description
      source
      sourcePort
      destination
      destinationPort
      protocol
      direction
      action
      appId
	  throttleRate
      weight
      organization
    }
  }
}

{
  "where": {
    "subjectType": { "_eq": "user" },
    "subjectId": { "_eq": "6e9bf365-8c09-4dd9-b9b2-83f6ab315618" }
  },
  "limit": 2,
  "orderBy": [{ "updatedAt": "desc_nulls_last" }]
}


### search active policies
# @name searchPolicies
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

query SearchPolicies($where: policies_bool_exp, $limit: Int = 50, $offset: Int = 0, $orderBy: [policies_order_by!] = [{updatedAt: desc_nulls_last}]) {
  policies(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) {
    id
    weight
    active
    validFrom
    validTo
    subjectId
    subjectType
    subjectDisplayName
    subjectSecondaryId
    createdBy
    createdAt
    updatedAt
    updatedBy
    organization
    rule {
      id
      displayName
      description
      tags
      annotations
      shared
      source
      sourcePort
      destination
      destinationPort
      protocol
      direction
      action
      appId
	  throttleRate
      weight
      createdBy
      createdAt
      updatedAt
      updatedBy
      organization
    }
  }
}


{
  "where": {
    "subjectType": { "_eq": "user" },
    "subjectId": { "_eq": "6e9bf365-8c09-4dd9-b9b2-83f6ab315618" }
  },
  "limit": 2,
  "orderBy": [{ "updatedAt": "desc_nulls_last" }]
}

###
@firstPoliciyId =  {{searchPolicies.response.body.$.data.policies[0].id}}
###

### getPolicy by Id
# @name getPolicy
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

query GetPolicy($id: uuid!) {
  policies_by_pk(id: $id) {
    id
    weight
    active
    validFrom
    validTo
    subjectId
    subjectType
    subjectDisplayName
    subjectSecondaryId
    createdBy
    createdAt
    updatedAt
    updatedBy
    organization
    rule {
      id
      displayName
      description
      tags
      annotations
      shared
      source
      sourcePort
      destination
      destinationPort
      protocol
      direction
      action
      appId
	  throttleRate
      weight
      createdBy
      createdAt
      updatedAt
      updatedBy
      organization
    }
  }
}

{
  "id": "{{firstPoliciyId}}"
}

###
@firstPolicyRuleId =  {{getPolicy.response.body.$.data.policies_by_pk.rule.id}}
###

### update policiy by ID
# FIXME: https://github.com/hasura/graphql-engine/issues/1573
# organization = x-hasura-org-id 	updatedBy = x-hasura-user-id
# @name updatePolicy
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

mutation UpdatePolicy($policyId: uuid!, $policyData: policies_set_input!,  $ruleId: uuid!,$ruleData: rules_set_input!) {
  update_policies_by_pk(pk_columns: {id: $policyId}, _set: $policyData) {
   id
    weight
    active
    validFrom
    validTo
    subjectId
    subjectType
    subjectDisplayName
    subjectSecondaryId
    createdBy
    createdAt
    updatedAt
    updatedBy
    organization
    rule {
      id
      displayName
      description
      tags
      annotations
      shared
      source
      sourcePort
      destination
      destinationPort
      protocol
      direction
      action
      appId
	  throttleRate
      weight
      createdBy
      createdAt
      updatedAt
      updatedBy
      organization
    }
  }
  update_rules_by_pk(pk_columns: {id: $ruleId}, _set: $ruleData) {
    id
  }
}

{
  "policyId":"{{firstPoliciyId}}",
  "policyData":{
		"weight": 501,
		"active": true,
		"validTo":"2024-05-21 00:59:07.11014+00"
  },
  "ruleId":"{{firstPolicyRuleId}}",
  "ruleData":{
    "displayName":"block youtube {{$randomInt 5 200}}",
    "description":"block youtube policy",
    "tags":["tz","us"],
    "annotations":"sumo2=>demo2",
    "weight": 670,
    "action": "block",
    "direction": "egress",
    "protocol": "Any",
    "appId":"myapp.exe",
	"throttleRate": "75",
    "destination":"1.1.1.1",
    "destinationPort":"443",
    "source":"0.0.0.0",
    "sourcePort":"5000"
	}
}

### create new policiy
# organization = x-hasura-org-id 	createdBy = x-hasura-user-id
# @name createPolicy
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

mutation CreatePolicy($data: policies_insert_input!) {
  insert_policies_one(object: $data) {
    id
    weight
    active
    validFrom
    validTo
    subjectId
    subjectType
    subjectDisplayName
    subjectSecondaryId
    createdBy
    createdAt
    updatedAt
    updatedBy
    organization
    rule {
      id
      displayName
      description
      tags
      annotations
      shared
      source
      sourcePort
      destination
      destinationPort
      protocol
      direction
      action
      appId
	  throttleRate
      weight
      createdBy
      createdAt
      updatedAt
      updatedBy
      organization
    }
  }
}

{
	"data": {
		"weight": 500,
		"active": true,
		"validFrom":"{{$datetime rfc1123|iso8601 [offset option]}}",
		"validTo":"2024-05-21 00:59:07.11014+00",
		"subjectId":"6e9bf365-8c09-4dd9-b9b2-83f6ab315618",
		"subjectType":"user",
		"subjectDisplayName":"sumanth chinthagunta",
		"subjectSecondaryId":"xmlking@gmail.com",
		"rule": {
			"data": {
				"displayName":"block youtube {{$randomInt 5 200}}",
				"description":"block youtube policy",
				"tags":["tz","us"],
				"annotations":"\"sumo\"=>\"demo\"",
				"shared": false,
				"weight": 670,
				"action": "block",
				"direction": "egress",
				"protocol": "Any",
				"appId":"myapp.exe",
				"throttleRate": "85",
				"destination":"1.1.1.1",
				"destinationPort":"443",
				"source":"0.0.0.0",
				"sourcePort":"5000"
			}
		}
	}
}

###
@createdPoliciyId =  {{createPolicy.response.body.$.data.insert_policies_one.id}}
@createdPolicyRuleId =  {{createPolicy.response.body.$.data.insert_policies_one.rule.id}}
###

### delete policiy
# if null returned, either ID is not found or this user don't have permissions to delete
# @name deletePolicyFail
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

mutation DeletePolicyFail($id:uuid!) {
  delete_policies_by_pk(id:  $id) {
      displayName
  }
}

{
  "id": "{{createdPoliciyId}}"
}

### delete policiy
# if Role's `shared=false`, delete `Policy` and assocated `Rule`, otherwise only delete `Policy`
# @name deletePolicy
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles: user manager
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

mutation DeletePolicy($policyId: uuid!, $ruleId: uuid!, $deletedAt: timestamptz!) {
  update_policies_by_pk(pk_columns: {id: $policyId}, _set: {deletedAt: $deletedAt}) {
    id
  }
  update_rules(where: {shared: {_eq: false}, id: {_eq: $ruleId}}, _set: {deletedAt: $deletedAt}) {
    affected_rows
    returning {
      id
	  displayName
    }
  }
}


{
  "policyId":"{{createdPoliciyId}}",
  "ruleId": "{{createdPolicyRuleId}}",
  "deletedAt": "{{$localDatetime iso8601}}"
}


# mutation DeletePolicy($policyId: uuid!, $ruleId: uuid!, $deletedAt: timestamptz!) {
#   update_policies_by_pk(pk_columns: {id: $policyId}, _set: {deletedAt: $deletedAt}) {
#     id
#   }
#   update_rules_by_pk(pk_columns: {id: $ruleId}, _set: {deletedAt: $deletedAt}) {
#     id
#   }
# }
