###
@graphqlEndpoint =  {{$dotenv HASURA_GRAPHQL_ENDPOINT}}/v1/graphql
@graphqlAdminToken = {{$dotenv HASURA_GRAPHQL_ADMIN_SECRET}}
# set token without `''`
@graphqlUserToken =
###

### IntrospectionQuery
# @name IntrospectionQuery
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
x-hasura-admin-secret: {{graphqlAdminToken}}

query IntrospectionQuery {
	__schema {
		types {
			name
			description
		}
		directives {
			name
			description
			locations
		}
	}
}

### List Active Pools
# @name listPools
POST  {{graphqlEndpoint}}
X-REQUEST-TYPE: GraphQL
Content-Type: application/json
Authorization: Bearer {{graphqlUserToken}}
x-hasura-admin-secret: {{graphqlAdminToken}}
x-hasura-allowed-roles:  user manager
x-hasura-role: manager
x-hasura-org-id: chinthagunta
x-hasura-user-id: xmlking@gmail.com

query SearchPoolsAndDevices($limit: Int = 10, $offset: Int = 0, $filter: String!) {
  pools(limit: $limit, offset: $offset, where: {displayName: {_like: $filter}}, order_by: [{updatedAt: desc_nulls_last}]) {
    id
    displayName
  }
  devices(limit: $limit, offset: $offset, where: {displayName: {_like: $filter}}, order_by: [{updatedAt: desc_nulls_last}]) {
    id
    displayName
  }
}

{
  "filter": "%%"
}
