query SettingsData($id: OrgIdFromSession!) {
  organizations_by_pk(id: $id) {
    ...SettingsFragment
    ...SettingsWithDefaultsFragment
  }
  settings_metadata(order_by: { key: asc }) {
    key
    description
    allowed_values
    default_value
  }
}
