query OrgSettings($id: OrgIdFromSession!) {
  organizations_by_pk(id: $id) {
    ...OrgSettingsFragment
    ...OrgDefSettingsFragment
  }
  setting_keys {
    key
    description
    allowed_values
    default_value
  }
}
