apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: web
  app.kubernetes.io/instance: web-abcxzy
  app.kubernetes.io/component: microservice

namePrefix: web-

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: env-vars
    literals:
      - MICRO_SERVER_NAME=gkit.service.web
      # - MICRO_SERVER_ADVERTISE="$(WEB_SERVICE_ENDPOINT):8080"
      # - DATABASE_HOST=$(DATABASE_ENDPOINT)

# vars:
#   - name: WEB_SERVICE_ENDPOINT
#     objref:
#       kind: Service
#       name: service
#       apiVersion: v1
#     fieldref:
#       fieldpath: metadata.name
