apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  clusterIP: None # headless service
  publishNotReadyAddresses: true # We want the servers to become available even if they're not ready
  ports:
    - name: http
      port: 3000 # no targetPort for headless service
      protocol: TCP
