apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: hasura-postgres
      app.kubernetes.io/instance: hasura-postgres-abcxzy
      app.kubernetes.io/component: database

namePrefix: hasura2-

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: env-vars
    literals:
      - PGDATA=/var/lib/postgresql/data/pgdata
