apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-claim
  labels:
    component: postgres
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
