blank_issues_enabled: false
contact_links:
  - name: Issue with the Packages ?
    url: https://github.com/xmlking/spectacular/issues/new/choose
    about: Please report issues for the packages in it's project
  - name: Get support on Discord
    url: https://discord.com/channels/xxx/xxx
    about: Get help from the maintainers on Discord
  - name: Ask a question, give feedback, share your project
    url: https://github.com/xmlking/spectacular/discussions
    about: Connect with other community members with GitHub discussions
