apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Please don't change the namespace field
#namespace: $(NS)
namespace: development
namePrefix: dev-
nameSuffix: -v1

labels:
  - includeSelectors: true
    pairs:
      environment: development
      app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am development!

resources:
  - ../../base/service
  - ../../base/envoy

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  #  - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - PUBLIC_GRAPHQL_ENDPOINT=https://hasura.localhost.direct/v1/graphql
      - AUTH_CLIENT_URL=https://console.localhost.direct:5173
      - PUBLIC_NHOST_SUBDOMAIN=local
      - PUBLIC_NHOST_REGION=
      - NHOST_HASURA_URL=https://hasura.localhost.direct/console
      - NHOST_AUTH_URL=https://auth.localhost.direct/v1
      - NHOST_GRAPHQL_URL=https://hasura.localhost.direct/v1
      - NHOST_STORAGE_URL=https://storage.localhost.direct/v1
      - NHOST_FUNCTIONS_URL=https://functions.localhost.direct/v1
      # - INSECURE_SKIP_VERIFY=true
      # following endpoint overwrites (in config.yml)
      # - CONFY_SERVICES_ACCOUNT_ENDPOINT=$(ACCOUNT_SERVICE_ENDPOINT)
      # - CONFY_SERVICES_GREETER_ENDPOINT=$(GREETER_SERVICE_ENDPOINT)
      # - CONFY_SERVICES_EMAILER_SERVICE_ENDPOINT=$(EMAILER_SERVICE_ENDPOINT)
      # - CONFY_SERVICES_RECORDER_ENDPOINT=$(RECORDER_SERVICE_ENDPOINT)

secretGenerator:
  - name: secrets
    behavior: merge # replace
    literals:
      - POSTGRES_PASSWORD=dev-real-pass

generatorOptions:
  disableNameSuffixHash: true

replicas:
  - name: service
    count: 1

images:
  - name: ghcr.io/xmlking/account
    newName: us-west1-docker.pkg.dev/my-123/docker/account
    newTag: v0.12.72
  - name: ghcr.io/xmlking/console
    newName: us-west1-docker.pkg.dev/my-123/docker/console
    # newTag: v0.25.0
    newTag: $(IMAGE_VERSION)
  - name: hasura/graphql-engine
    newName: us-west1-docker.pkg.dev/my-123/docker/hasura/graphql-engine
    newTag: v2.37.0
  - name: traefik
    newName: us-west1-docker.pkg.dev/my-123/docker/traefik
    newTag: v3.0
  - name: postgres
    newName: us-west1-docker.pkg.dev/my-123/docker/postgres
    newTag: '16'
  - name: nhost/hasura-auth
    newName: us-west1-docker.pkg.dev/my-123/docker/hasura-auth
    newTag: '0.25'
  - name: nhost/hasura-storage
    newName: us-west1-docker.pkg.dev/my-123/docker/hasura-storage
    newTag: '0.6.0'
  - name: nhost/dashboard
    newName: us-west1-docker.pkg.dev/my-123/docker/nhost/dashboard
    newTag: '1.6.3'
