apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres
  - hasura
  - hasura-auth
  - app

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: signals
      app.kubernetes.io/managed-by: kustomize
commonAnnotations:
  org: home-and-community

configMapGenerator:
  #  - name: env-vars
  #    behavior: merge
  - name: env-vars-common
    behavior: merge
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

configurations:
  - kconfig.yaml

secretGenerator:
  - name: secrets
    literals:
      - POSTGRES_PASSWORD=postgres
      - HASURA_GRAPHQL_ADMIN_SECRET=nhost-admin-secret
      - HASURA_GRAPHQL_JWT_SECRET_KEY=fake
