## DYNAMIC CONFIGURATION
tls:
  certificates:
    - certFile: /etc/traefik/certs/localhost.direct.crt
      keyFile: /etc/traefik/certs/localhost.direct.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/localhost.direct.crt
        keyFile: /etc/traefik/certs/localhost.direct.key
  # when troubleshooting certs, enable this so traefik doesn't use
  # its own self-signed. By default if it can't find a matching
  # cert, it'll just create its own which will cause cert warnings
  # in browser and can be confusing to troubleshoot
#  options:
#    default:
#      sniStrict: true


# Declaring the user list
#
# Note: when used in docker-compose.yml all dollar signs in the hash need to be doubled for escaping.
# To create a user:password pair, the following command can be used:
# echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
#
# Also note that dollar signs should NOT be doubled when they not evaluated (e.g. Ansible docker_container module).
http:
  # Add the middleware
  middlewares:
    my-basic-auth:
      basicAuth:
        users:
        - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
        - test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0
        usersFile: /etc/traefik/.htpasswd
