## DYNAMIC CONFIGURATION
tls:
  certificates:
    - certFile: /etc/ssl/traefik/traefik.me.crt
      keyFile: /etc/ssl/traefik/traefik.me.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/traefik/traefik.me.crt
        keyFile: /etc/ssl/traefik/traefik.me.key
  # when troubleshooting certs, enable this so traefik doesn't use
  # its own self-signed. By default if it can't find a matching
  # cert, it'll just create its own which will cause cert warnings
  # in browser and can be confusing to troubleshoot
#  options:
#    default:
#      sniStrict: true

