## STATIC CONFIGURATION
global:
  sendAnonymousUsage: false

# set to DEBUG if needed
log:
  level: INFO

ping:
  entryPoint: web

api:
  dashboard: true
  insecure: true

providers: # You can add more than one provider if needed
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false # Only expose explicitly enabled containers
    watch: true
    defaultRule: 'HostRegexp(`{{ index .Labels "com.docker.compose.service"}}.traefik.me`,`{{ index .Labels "com.docker.compose.service"}}-{dashed-ip:.*}.traefik.me`)'
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# listen on 80/443, and redirect all 80 to 443 via 301
entryPoints:
  web:
    address: :80
    # comment out these lins if you don't want to redirect everything
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
# TODO: https://github.com/mead-team/oknawa-backend-server/blob/main/docker-compose.dev.yml
#certificatesResolvers:
#  acme:
#    acme:
#      email: brian.takita@gmail.com
#      storage: /letsencrypt/acme.json
#      httpChallenge:
#        entryPoint: web

## DYNAMIC CONFIGURATION
