apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  serviceName: postgres-headless
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
        role: master
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                exec pg_isready \
                	-U "${POSTGRES_USER}" \
                	-d "dbname=${POSTGRES_DB}" \
                	-h 127.0.0.1 \
                	-p 5432
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                exec pg_isready \
                	-U "${POSTGRES_USER}" \
                	-d "dbname=${POSTGRES_DB}" \
                	-h 127.0.0.1 \
                	-p 5432
        ports:
        - name: postgres
          containerPort: 5432
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: initdb
          configMap:
            name: postgres-initdb
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
