apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres-abcxzy
    app.kubernetes.io/component: infra

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: postgres-initdb
    files:
      - initdb.sql

secretGenerator:
  - name: postgres
    literals:
      - username=postgres
      - password=postgres
    type: kubernetes.io/basic-auth

# replacements:
#   - path: replacement.yaml
# vars:
# - name: POSTGRES_SERVICE_ENDPOINT
#   objref:
#     kind: Service
#     name: postgres
#     apiVersion: v1
#   fieldref:
#     fieldpath: metadata.name
