query ListPolicies2(
	$limit: Int = 50
	$offset: Int = 0
	$orderBy: [PoliciesOrderBy!] = [{ updatedAt: DESC_NULLS_LAST }]
) @cache(policy: CacheAndNetwork) @load {
	policies(orderBy: $orderBy, limit: $limit, offset: $offset) @paginate {
		...Policy_list_fields @mask_disable
	}
}
