name = 'clamav-service'

[image]
image = 'nhost/clamav:0.1.2'

[[environment]]
name="ENV"
value="prod"

[[ports]]
type="http"
port = 3310
publish = true

[resources]
replicas = 1

[resources.compute]
cpu = 62
memory = 128
