name="console"

[image]
image = "ghcr.io/threatmatic/cybernetics/console:0.4.4"
# image="registry.eu-central-1.nhost.run/b719c4a4-6fb2-4feb-8220-c7f01ef5bfe8:0.1.1"

[[environment]]
name = "ENV"
value = "prod"

[[ports]]
type="http"
port = 3000
publish = true

[resources]
replicas = 1

[resources.compute]
cpu = 62
memory = 128

[[resources.storage]]
name="data"
path="/var/lib/data"
capacity=1
