[hasura]
version = 'v2.44.0-ce'
adminSecret = '{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}'
webhookSecret = '{{ secrets.NHOST_WEBHOOK_SECRET }}'

[[hasura.jwtSecrets]]
type = 'HS256'
key = '{{ secrets.HASURA_GRAPHQL_JWT_SECRET }}'

# [[hasura.jwtSecrets.claims_map]]
# claim = "x-hasura-allowed-roles"
# path = "$.https://hasura.io/jwt/claims.tenant-roles"
# default = ["user", "editor"]

[hasura.settings]
corsDomain = ['*']
devMode = true
enableAllowList = false
enableConsole = true
enableRemoteSchemaPermissions = false
enabledAPIs = ['metadata', 'graphql', 'pgdump', 'config']
inferFunctionPermissions = true
liveQueriesMultiplexedRefetchInterval = 1000
stringifyNumericTypes = false
unauthorizedRole = 'public'

[hasura.logs]
level = 'warn'

[hasura.events]
httpPoolSize = 100

[graphql]
[graphql.security]
forbidAminSecret = false
maxDepthQueries = 4

[functions]
[functions.node]
version = 20

[auth]
version = '0.36.1'

[auth.elevatedPrivileges]
mode = 'required'

[auth.redirections]
clientUrl = 'https://console.traefik.me:5173'
allowedUrls = ['https://console.traefik.me:5173', 'https://console.traefik.me:5173/profile', 'https://console.traefik.me:4173', 'https://console.traefik.me:4173/profile', 'https://console.traefik.me:3000', 'https://console.traefik.me:3000/profile', 'https://console.traefik.me', 'https://console.traefik.me/profile', 'https://*.vercel.app']

[auth.signUp]
enabled = true
disableNewUsers = false

# TODO: https://docs.nhost.io/guides/auth/bot-protection
# [auth.signUp.turnstile]
# secretKey = 'turnstileSecretKey'

[auth.user]
[auth.user.roles]
default = 'user'
allowed = ['user', 'me']

[auth.user.locale]
default = 'en'
allowed = ['en', 'de', 'es']

[auth.user.gravatar]
enabled = true
default = 'mp'
rating = 'g'

[auth.user.email]

[auth.user.emailDomains]

[auth.session]
[auth.session.accessToken]
expiresIn = 900

[[auth.session.accessToken.customClaims]]
key = 'Org-Id'
value = 'currentOrgId'

[[auth.session.accessToken.customClaims]]
key = 'Org-Ids'
value = 'allowedOrgs.orgId[]'

[[auth.session.accessToken.customClaims]]
key = 'user-email'
value = 'email'

[auth.session.refreshToken]
expiresIn = 2592000

[auth.method]
[auth.method.anonymous]
enabled = false

[auth.method.emailPasswordless]
enabled = true

[auth.method.otp]
[auth.method.otp.email]
enabled = true

[auth.method.emailPassword]
hibpEnabled = false
emailVerificationRequired = false
passwordMinLength = 9

[auth.method.smsPasswordless]
enabled = false

[auth.method.oauth]
[auth.method.oauth.apple]
enabled = false

[auth.method.oauth.azuread]
enabled = true
tenant = '{{ secrets.AUTH_PROVIDER_AZUREAD_TENANT }}'
clientId = '{{ secrets.AUTH_PROVIDER_AZUREAD_CLIENT_ID }}'
clientSecret = '{{ secrets.AUTH_PROVIDER_AZUREAD_CLIENT_SECRET }}'

[auth.method.oauth.bitbucket]
enabled = false

[auth.method.oauth.discord]
enabled = false

[auth.method.oauth.facebook]
enabled = false

[auth.method.oauth.github]
enabled = true
clientId = '{{ secrets.AUTH_PROVIDER_GITHUB_CLIENT_ID }}'
scope = ['openid', 'email', 'profile']
clientSecret = '{{ secrets.AUTH_PROVIDER_GITHUB_CLIENT_SECRET }}'

[auth.method.oauth.gitlab]
enabled = false

[auth.method.oauth.google]
enabled = true
clientId = '{{ secrets.AUTH_PROVIDER_GOOGLE_CLIENT_ID }}'
scope = ['openid', 'email', 'profile']
clientSecret = '{{ secrets.AUTH_PROVIDER_GOOGLE_CLIENT_SECRET }}'

[auth.method.oauth.linkedin]
enabled = false

[auth.method.oauth.spotify]
enabled = false

[auth.method.oauth.strava]
enabled = false

[auth.method.oauth.twitch]
enabled = false

[auth.method.oauth.twitter]
enabled = false

[auth.method.oauth.windowslive]
enabled = false

[auth.method.oauth.workos]
enabled = false

[auth.method.webauthn]
enabled = true

[auth.method.webauthn.relyingParty]
name = 'Spectacular Console App'
origins = ['https://console.traefik.me:5173']

[auth.method.webauthn.attestation]
timeout = 60000

[auth.totp]
enabled = false

[auth.misc]
concealErrors = false

[auth.rateLimit]
[auth.rateLimit.emails]
limit = 10
interval = '1h'

[auth.rateLimit.sms]
limit = 10
interval = '1h'

[auth.rateLimit.bruteForce]
limit = 10
interval = '5m'

[auth.rateLimit.signups]
limit = 10
interval = '5m'

[auth.rateLimit.global]
limit = 100
interval = '1m'

[postgres]
version = '16.4-202401126-1'

[postgres.resources]
enablePublicAccess = true

[postgres.settings]
maxConnections = 100
walLevel = 'logical'
maxWalSenders = 10
maxReplicationSlots = 10

[provider]
[provider.smtp]
user = '{{ secrets.AUTH_SMTP_USER }}'
password = '{{ secrets.AUTH_SMTP_PASS }}'
sender = '{{ secrets.AUTH_SMTP_SENDER }}'
host = '{{ secrets.AUTH_SMTP_HOST }}'
port = 1025
secure = false
method = 'PLAIN'

# [provider.sms]
# provider = 'twilio'
# accountSid = 'twilioAccountSid'
# authToken = 'twilioAuthToken'
# messagingServiceId = 'twilioMessagingServiceId'

[storage]
version = '0.6.1'

# [storage.antivirus]
# server = 'tcp://run-clamav:3310'

[ai]
version = '0.6.1'
webhookSecret = '{{ secrets.GRAPHITE_WEBHOOK_SECRET }}'

[ai.resources]
[ai.resources.compute]
cpu = 256
memory = 512

[ai.openai]
organization = '{{ secrets.OPENAI_ORG_ID }}'
apiKey = '{{ secrets.OPENAI_API_KEY }}'

[ai.autoEmbeddings]
synchPeriodMinutes = 10

[observability]
[observability.grafana]
adminPassword = '{{ secrets.GRAFANA_ADMIN_PASSWORD }}'
