[global]
[[global.environment]]
name = 'APP_NAME'
value = 'Spectacular'

[[global.environment]]
name = 'APP_DESCRIPTION'
value = 'Spectacular Console App'

[hasura]
version = 'v2.38.0-ce'
adminSecret = '{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}'
webhookSecret = '{{ secrets.NHOST_WEBHOOK_SECRET }}'

[[hasura.jwtSecrets]]
type = 'HS256'
key = '{{ secrets.HASURA_GRAPHQL_JWT_SECRET_KEY }}'

[hasura.settings]
corsDomain = ['*']
devMode = true
enableAllowList = false
enableConsole = true
enableRemoteSchemaPermissions = false
enabledAPIs = ['metadata', 'graphql', 'pgdump', 'config']
liveQueriesMultiplexedRefetchInterval = 3000

[hasura.logs]
level = 'warn'

[hasura.events]
httpPoolSize = 100

[hasura.resources]
replicas = 1

[hasura.resources.compute]
cpu = 500
memory = 1536

[graphql]
[graphql.security]
maxDepthQueries = 4

[functions]
[functions.node]
version = 18

[auth]
version = '0.29.3'

[auth.resources]
replicas = 1

[auth.resources.compute]
cpu = 250
memory = 256

[auth.elevatedPrivileges]
mode = 'required'

[auth.redirections]
clientUrl = 'https://console.traefik.me:5173'
allowedUrls = ['https://console.traefik.me:5173', 'https://console.traefik.me:5173/dashboard/profile', 'https://console.traefik.me:3000', 'https://console.traefik.me:3000/dashboard/profile', 'https://console.traefik.me', 'https://console.traefik.me/dashboard/profile', 'https://*.vercel.app']

[auth.signUp]
enabled = true
disableNewUsers = false

[auth.user]
[auth.user.roles]

[auth.user.locale]
default = 'en'
allowed = ['en', 'de', 'es']

[auth.user.gravatar]
enabled = true
default = 'mp'
rating = 'g'

[auth.user.email]

[auth.user.emailDomains]

[auth.session]
[auth.session.accessToken]
expiresIn = 900

[[auth.session.accessToken.customClaims]]
key = 'allowed-orgs'
value = 'organizations[].organization'

[[auth.session.accessToken.customClaims]]
key = 'default-org'
value = 'metadata.default_org'

[[auth.session.accessToken.customClaims]]
key = 'user-email'
value = 'email'

[auth.session.refreshToken]
expiresIn = 2592000

[auth.method]
[auth.method.anonymous]
enabled = false

[auth.method.emailPasswordless]
enabled = true

[auth.method.emailPassword]
hibpEnabled = false
emailVerificationRequired = false
passwordMinLength = 9

[auth.method.smsPasswordless]
enabled = false

[auth.method.oauth]
[auth.method.oauth.apple]
enabled = false

[auth.method.oauth.azuread]
tenant = '{{ secrets.AUTH_PROVIDER_AZUREAD_TENANT }}'
enabled = true
clientId = '{{ secrets.AUTH_PROVIDER_AZUREAD_CLIENT_ID }}'
clientSecret = '{{ secrets.AUTH_PROVIDER_AZUREAD_CLIENT_SECRET }}'

[auth.method.oauth.bitbucket]
enabled = false

[auth.method.oauth.discord]
enabled = false

[auth.method.oauth.facebook]
enabled = false

[auth.method.oauth.github]
enabled = true
clientId = '{{ secrets.AUTH_PROVIDER_GITHUB_CLIENT_ID }}'
clientSecret = '{{ secrets.AUTH_PROVIDER_GITHUB_CLIENT_SECRET }}'

[auth.method.oauth.gitlab]
enabled = false

[auth.method.oauth.google]
enabled = true
clientId = '{{ secrets.AUTH_PROVIDER_GOOGLE_CLIENT_ID }}'
clientSecret = '{{ secrets.AUTH_PROVIDER_GOOGLE_CLIENT_SECRET }}'

[auth.method.oauth.linkedin]
enabled = false

[auth.method.oauth.spotify]
enabled = false

[auth.method.oauth.strava]
enabled = false

[auth.method.oauth.twitch]
enabled = false

[auth.method.oauth.twitter]
enabled = false

[auth.method.oauth.windowslive]
enabled = false

[auth.method.oauth.workos]
enabled = false

[auth.method.webauthn]
enabled = true

[auth.method.webauthn.relyingParty]
id = 'Spectacular'
name = 'Spectacular Console App'
origins = ['https://console.traefik.me:5173', 'https://console.traefik.me']

[auth.method.webauthn.attestation]
timeout = 60000

[auth.totp]
enabled = true
issuer = 'Spectacular'

[postgres]
version = '14.11-20240429-1'

[postgres.resources]
replicas = 1

[postgres.resources.compute]
cpu = 1000
memory = 2048

[postgres.settings]
maxConnections = 100
walLevel = 'logical'
maxWalSenders = 1
maxReplicationSlots = 1

[provider]
[provider.smtp]
user = '{{ secrets.AUTH_SMTP_USER }}'
password = '{{ secrets.AUTH_SMTP_PASS }}'
sender = '{{ secrets.AUTH_SMTP_SENDER }}'
host = '{{ secrets.AUTH_SMTP_HOST }}'
port = 1025
secure = false
method = '{{ secrets.AUTH_SMTP_AUTH_METHOD }}'

[storage]
version = '0.6.0'

[storage.resources]
replicas = 1

[storage.resources.compute]
cpu = 250
memory = 256

[ai]
version = '0.5.2'
webhookSecret = '{{ secrets.GRAPHITE_WEBHOOK_SECRET }}'

[ai.resources]
[ai.resources.compute]
cpu = 187
memory = 384

[ai.openai]
organization = 'my-org'
apiKey = '{{ secrets.OPENAI_API_KEY }}'

[ai.autoEmbeddings]
synchPeriodMinutes = 10

[observability]
[observability.grafana]
adminPassword = '{{ secrets.GRAFANA_ADMIN_PASSWORD }}'
