apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Please don't change the namespace field
#namespace: $(NS)
namespace: production
namePrefix: prod-
nameSuffix: -v1

labels:
  - includeSelectors: true
    pairs:
      environment: production
      app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am production!

resources:
  - ../../base/service

configMapGenerator:
  #  - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - PUBLIC_GRAPHQL_ENDPOINT=https://hasura.localhost.direct/v1/graphql
      - AUTH_CLIENT_URL=https://console.localhost.direct:5173
      - PUBLIC_NHOST_SUBDOMAIN=local
      - PUBLIC_NHOST_REGION=
      - NHOST_HASURA_URL=https://hasura.localhost.direct/console
      - NHOST_AUTH_URL=https://auth.localhost.direct/v1
      - NHOST_GRAPHQL_URL=https://hasura.localhost.direct/v1
      - NHOST_STORAGE_URL=https://storage.localhost.direct/v1
      - NHOST_FUNCTIONS_URL=https://functions.localhost.direct/v1

secretGenerator:
  - name: secrets
    behavior: merge
    literals:
      - POSTGRES_PASSWORD=prod-real-pass
  # - name: registry-credentials
  #   files:
  #       - ".dockerconfigjson=docker.secret.json"
  #   type: kubernetes.io/dockerconfigjson

replicas:
  - name: service
    count: 1

images:
  - name: ghcr.io/xmlking/account
    newName: us-west1-docker.pkg.dev/my-123/docker/account
    newTag: v0.12.72
  - name: ghcr.io/xmlking/console
    newName: us-west1-docker.pkg.dev/my-123/docker/console
    # newTag: v0.25.0
    newTag: $(IMAGE_VERSION)
  - name: hasura/graphql-engine
    newName: us-west1-docker.pkg.dev/my-123/docker/hasura/graphql-engine
    newTag: v2.37.0
  - name: traefik
    newName: us-west1-docker.pkg.dev/my-123/docker/traefik
    newTag: v3.0
  - name: postgres
    newName: us-west1-docker.pkg.dev/my-123/docker/postgres
    newTag: '16'
  - name: nhost/hasura-auth
    newName: us-west1-docker.pkg.dev/my-123/docker/hasura-auth
    newTag: '0.25'
  - name: nhost/hasura-storage
    newName: us-west1-docker.pkg.dev/my-123/docker/hasura-storage
    newTag: '0.6.0'
  - name: nhost/dashboard
    newName: us-west1-docker.pkg.dev/my-123/docker/nhost/dashboard
    newTag: '1.6.3'
