query OrgSettingsData($id: OrgIdFromSession!) {
  organizations_by_pk(id: $id) {
    ...OrgSettingsFragment
    ...OrgSettingsWithDefaultsFragment
  }
  settings_metadata(order_by: { key: asc }, where: { type: { _eq: org } }) {
    key
    description
    allowedValues
    defaultValue
  }
}
