query SearchRulesPage(
  $where: rules_bool_exp
  $limit: Int = 50
  $offset: Int = 0
  $orderBy: [rules_order_by!] = [{ updatedAt: desc_nulls_last }]
) @loading(cascade: true) {
  rules(where: $where, order_by: $orderBy, limit: $limit, offset: $offset) @list(name: "Search_Rules")  {
    ... on rules {
      id
      displayName
      description
      source
      sourcePort
      destination
      destinationPort
      protocol
      action
      direction
      appId
      throttleRate
      weight
      shared
      updatedAt
    }
  }
}
