apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: hasura
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgresql://$(PGUSER)@postgresql/prefect
