mutation Updatenonhomeroles(
  $userId: uuid!
  $orgId: uuid!
  $defrole: String
  $delroles: [String!]!
  $roles: [user_org_roles_insert_input!]!
) {
  delete_user_org_roles(where: { userId: { _eq: $userId }, orgId: { _eq: $orgId }, role: { _in: $delroles } }) {
    affected_rows
  }

  insert_user_org_roles(objects: $roles) {
    returning {
      userId
      orgId
    }
  }

  update_user_org_roles(
    where: { userId: { _eq: $userId }, orgId: { _eq: $orgId }, role: { _eq: $defrole } }
    _set: { isCurrentOrg: true }
  ) {
    affected_rows
  }

  forother: update_user_org_roles(
    where: { userId: { _eq: $userId }, orgId: { _eq: $orgId }, role: { _neq: $defrole } }
    _set: { isCurrentOrg: false }
  ) {
    affected_rows
  }
}
