mutation Updatenonhomeroles(
  $userId: uuid!
  $Org: String
  $defrole: String
  $delroles: [String!]!
  $roles: [user_org_roles_insert_input!]!
) {
  delete_user_org_roles(where: { userId: { _eq: $userId }, organization: { _eq: $Org }, role: { _in: $delroles } }) {
    affected_rows
  }

  insert_user_org_roles(objects: $roles) {
    returning {
      id
      organization
    }
  }

  update_user_org_roles(
    where: { userId: { _eq: $userId }, organization: { _eq: $Org }, role: { _eq: $defrole } }
    _set: { isDefaultRole: true }
  ) {
    affected_rows
  }

  forother: update_user_org_roles(
    where: { userId: { _eq: $userId }, organization: { _eq: $Org }, role: { _neq: $defrole } }
    _set: { isDefaultRole: false }
  ) {
    affected_rows
  }
}
