mutation Updatehomeroles(
  $userId: uuid!
  $defaultRole: String
  $delroles: [String!]!
  $Authroles: [authUserRoles_insert_input!]!
) {
  updateUser(pk_columns: { id: $userId }, _set: { defaultRole: $defaultRole }) {
    defaultRole
    displayName
  }
  deleteAuthUserRoles(where: { userId: { _eq: $userId }, role: { _in: $delroles } }) {
    affected_rows
  }
  insertAuthUserRoles(objects: $Authroles) {
    returning {
      id
      role
    }
  }
}
