query GetUserById($id: uuid!) {
  user(id: $id) {
    id
    allowedOrgs {
      organization
    }
    defaultRole
    displayName
    email
    avatarUrl
    metadata
  }
  user_org_roles(where: { userId: { _eq: $id } }) {
    organization
    role
    isDefaultRole
  }
  organizations {
    organization
  }
  authUserRoles {
    role
  }
}
