query ListDevices($limit: Int = 50, $offset: Int = 0, $displayName: String = "%%")
@cache(policy: NetworkOnly) {
	devices(
		limit: $limit
		offset: $offset
		order_by: [{ updatedAt: desc_nulls_last }]
		where: { displayName: { _like: $displayName } }
	) {
		tags
		createdBy
		description
		displayName
		organization
		updatedBy
		createdAt
		updatedAt
		annotations
		id
		ip
		version
	}
}
