query GetUserById($id: uuid!) {
  user(id: $id) {
    id
    allowedOrgs {
      orgId
    }
    defaultRole
    displayName
    email
    avatarUrl
    metadata
  }
  user_org_roles(where: { userId: { _eq: $id } }) {
    orgId
    role
    isCurrentOrg
  }
  authUserRoles {
    role
  }
}
