query GetPolicy($id: uuid!) {
	policies_by_pk(id: $id) {
		weight
		active
		validFrom
		validTo
		subjectId
		subjectType
		subjectDisplayName
		subjectSecondaryId
		ruleId
		rule {
			displayName
			description
			tags
			annotations
			shared
			source
			sourcePort
			destination
			destinationPort
			protocol
			direction
			action
			appId
			throttleRate
			weight
		}
	}
}
