apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
spec:
  template:
    spec:
      containers:
        - name: hasura
          env:
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
