table:
  name: pools
  schema: public
array_relationships:
  - name: pool_devices
    using:
      foreign_key_constraint_on:
        column: pool_id
        table:
          name: device_pool
          schema: public
insert_permissions:
  - role: manager
    permission:
      check:
        organization:
          _eq: x-hasura-org-id
      set:
        created_by: x-hasura-user-id
        organization: x-hasura-org-id
        updated_by: x-hasura-user-id
      columns:
        - annotations
        - description
        - display_name
        - tags
  - role: user
    permission:
      check:
        organization:
          _eq: x-hasura-org-id
      set:
        created_by: x-hasura-user-id
        organization: x-hasura-org-id
        updated_by: x-hasura-user-id
      columns:
        - annotations
        - description
        - display_name
        - tags
select_permissions:
  - role: manager
    permission:
      columns:
        - tags
        - created_by
        - description
        - display_name
        - organization
        - updated_by
        - created_at
        - deleted_at
        - updated_at
        - annotations
        - id
      filter:
        _and:
          - deleted_at:
              _is_null: true
          - organization:
              _eq: x-hasura-org-id
  - role: user
    permission:
      columns:
        - tags
        - created_by
        - description
        - display_name
        - organization
        - updated_by
        - created_at
        - deleted_at
        - updated_at
        - annotations
        - id
      filter:
        _and:
          - created_by:
              _eq: x-hasura-user-id
          - organization:
              _eq: x-hasura-org-id
          - deleted_at:
              _is_null: true
update_permissions:
  - role: manager
    permission:
      columns:
        - annotations
        - deleted_at
        - description
        - display_name
        - tags
      filter:
        organization:
          _eq: x-hasura-org-id
      check: null
      set:
        organization: x-hasura-org-id
        updated_by: x-hasura-user-id
  - role: user
    permission:
      columns:
        - annotations
        - deleted_at
        - description
        - tags
      filter:
        _and:
          - created_by:
              _eq: x-hasura-user-id
          - organization:
              _eq: x-hasura-org-id
      check: null
      set:
        organization: x-hasura-org-id
        updated_by: x-hasura-user-id
delete_permissions:
  - role: manager
    permission:
      filter:
        organization:
          _eq: x-hasura-org-id
