table:
  name: rules
  schema: public
insert_permissions:
  - role: manager
    permission:
      check: {}
      set:
        created_by: x-hasura-user-id
        organization: x-hasura-org-id
        updated_by: x-hasura-user-id
      columns:
        - action
        - annotations
        - app_id
        - created_by
        - description
        - destination
        - destination_port
        - direction
        - display_name
        - protocol
        - shared
        - source
        - source_port
        - tags
        - throttle_rate
        - weight
  - role: user
    permission:
      check: {}
      set:
        created_by: x-hasura-user-id
        organization: x-hasura-org-id
        updated_by: x-hasura-user-id
      columns:
        - action
        - annotations
        - app_id
        - description
        - destination
        - destination_port
        - direction
        - display_name
        - protocol
        - shared
        - source
        - source_port
        - tags
        - throttle_rate
        - weight
select_permissions:
  - role: engine
    permission:
      columns:
        - action
        - app_id
        - description
        - destination
        - destination_port
        - direction
        - display_name
        - id
        - organization
        - protocol
        - source
        - source_port
        - throttle_rate
        - weight
      filter:
        _and:
          - deleted_at:
              _is_null: true
          - organization:
              _eq: x-hasura-org-id
  - role: manager
    permission:
      columns:
        - action
        - annotations
        - app_id
        - created_at
        - created_by
        - description
        - destination
        - destination_port
        - direction
        - display_name
        - id
        - organization
        - protocol
        - shared
        - source
        - source_port
        - tags
        - throttle_rate
        - updated_at
        - updated_by
        - weight
      filter:
        _and:
          - deleted_at:
              _is_null: true
          - organization:
              _eq: x-hasura-org-id
  - role: user
    permission:
      columns:
        - action
        - annotations
        - app_id
        - created_at
        - created_by
        - description
        - destination
        - destination_port
        - direction
        - display_name
        - id
        - organization
        - protocol
        - shared
        - source
        - source_port
        - tags
        - throttle_rate
        - updated_at
        - updated_by
        - weight
      filter:
        _and:
          - organization:
              _eq: x-hasura-org-id
          - created_by:
              _eq: x-hasura-user-Id
          - deleted_at:
              _is_null: true
update_permissions:
  - role: manager
    permission:
      columns:
        - action
        - annotations
        - app_id
        - deleted_at
        - description
        - destination
        - destination_port
        - direction
        - display_name
        - protocol
        - shared
        - source
        - source_port
        - tags
        - throttle_rate
        - weight
      filter:
        _and:
          - deleted_at:
              _is_null: true
          - organization:
              _eq: x-hasura-org-id
      check: {}
      set:
        updated_by: x-hasura-user-id
  - role: user
    permission:
      columns:
        - action
        - annotations
        - app_id
        - deleted_at
        - description
        - destination
        - destination_port
        - direction
        - display_name
        - protocol
        - shared
        - source
        - source_port
        - tags
        - throttle_rate
        - weight
      filter:
        _and:
          - organization:
              _eq: x-hasura-org-id
          - created_by:
              _eq: x-hasura-user-Id
          - deleted_at:
              _is_null: true
      check: {}
      set:
        updated_by: x-hasura-user-id
