apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Please don't change the namespace field
# namespace: $(NS)
namespace: local
namePrefix: dev-
nameSuffix: -v1

commonAnnotations:
  note: Hello, I am local!

resources:
  - namespace.yaml
  - ../../base

# components:
# - ../../components/console
# - ../../components/postgres

# replicas:
# - count: 1
#   name: service

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/version: v1
      environment: local

images:
  - name: postgres
    newTag: '16'
  - name: hasura/graphql-engine
    newTag: v2.35.1.cli-migrations-v3
